from socket import *
serverAddressPort = ('hostname' , 8080)
clientSocket = socket(AF_INET,SOCK_DGRAM)
print ("I2")
message = ("Input lowercase sentence: ")
print ("I1")
clientSocket.sendto(str.encode(message),(serverAddressPort))
modifiedMessage, serverAddress = clientSocket.recvfrom(2048)
print (modifiedMessage.decode())
clientSocket.close()